"""Add user role

Revision ID: 5ef5502d4230
Revises: 4141e30179c0
Create Date: 2025-10-19 21:28:47.032145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5ef5502d4230"
down_revision: Union[str, Sequence[str], None] = "4141e30179c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    enum = postgresql.ENUM("USER", "ADMIN", name="role")
    enum.create(op.get_bind())
    op.add_column("users", sa.Column("role", enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
